# Generated by Django 5.0.6 on 2025-06-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnas',
            options={'ordering': ['-created'], 'verbose_name': 'Alumna', 'verbose_name_plural': 'Alumnas'},
        ),
        migrations.AlterField(
            model_name='alumnas',
            name='matricula',
            field=models.CharField(max_length=12, verbose_name='Mat'),
        ),
    ]
