# Generated by Django 5.0.6 on 2025-06-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_alumnas_options_alter_alumnas_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnas',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='alumnas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
