# Generated by Django 5.2.2 on 2025-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentariocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultarComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
