# Generated by Django 5.0.6 on 2025-07-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_consultarcomentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultarComentario',
        ),
    ]
