# Generated by Django 5.0.6 on 2025-06-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12, verbose_name='Mat')),
                ('nombre', models.TextField()),
                ('carrera', models.TextField()),
                ('turno', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumna',
                'verbose_name_plural': 'Alumnas',
                'ordering': ['-created'],
            },
        ),
    ]
